// Package httpreceiver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpreceiver

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// AcceptedRequest defines model for AcceptedRequest.
type AcceptedRequest struct {
	EffectiveEnd   time.Time    `json:"effectiveEnd"`
	EffectiveStart time.Time    `json:"effectiveStart"`
	RequestId      string       `json:"requestId"`
	ScaledObject   ScaledObject `json:"scaledObject"`
}

// DeletedRequest defines model for DeletedRequest.
type DeletedRequest struct {
	EffectiveEnd   time.Time    `json:"effectiveEnd"`
	EffectiveStart time.Time    `json:"effectiveStart"`
	RequestId      string       `json:"requestId"`
	ScaledObject   ScaledObject `json:"scaledObject"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// LaunchRequest defines model for LaunchRequest.
type LaunchRequest struct {
	Duration     *string      `json:"duration,omitempty"`
	EndAt        *time.Time   `json:"endAt,omitempty"`
	RequestId    string       `json:"requestId"`
	ScaledObject ScaledObject `json:"scaledObject"`
	StartAt      *time.Time   `json:"startAt,omitempty"`
	union        json.RawMessage
}

// LaunchRequest0 defines model for .
type LaunchRequest0 = interface{}

// LaunchRequest1 defines model for .
type LaunchRequest1 = interface{}

// ScaledObject defines model for ScaledObject.
type ScaledObject struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

// ScaledObjectList defines model for ScaledObjectList.
type ScaledObjectList struct {
	ScaledObjects []ScaledObject `json:"scaledObjects"`
}

// PostRequestsJSONRequestBody defines body for PostRequests for application/json ContentType.
type PostRequestsJSONRequestBody = LaunchRequest

// AsLaunchRequest0 returns the union data inside the LaunchRequest as a LaunchRequest0
func (t LaunchRequest) AsLaunchRequest0() (LaunchRequest0, error) {
	var body LaunchRequest0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLaunchRequest0 overwrites any union data inside the LaunchRequest as the provided LaunchRequest0
func (t *LaunchRequest) FromLaunchRequest0(v LaunchRequest0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLaunchRequest0 performs a merge with any union data inside the LaunchRequest, using the provided LaunchRequest0
func (t *LaunchRequest) MergeLaunchRequest0(v LaunchRequest0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLaunchRequest1 returns the union data inside the LaunchRequest as a LaunchRequest1
func (t LaunchRequest) AsLaunchRequest1() (LaunchRequest1, error) {
	var body LaunchRequest1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLaunchRequest1 overwrites any union data inside the LaunchRequest as the provided LaunchRequest1
func (t *LaunchRequest) FromLaunchRequest1(v LaunchRequest1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLaunchRequest1 performs a merge with any union data inside the LaunchRequest, using the provided LaunchRequest1
func (t *LaunchRequest) MergeLaunchRequest1(v LaunchRequest1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LaunchRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Duration != nil {
		object["duration"], err = json.Marshal(t.Duration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'duration': %w", err)
		}
	}

	if t.EndAt != nil {
		object["endAt"], err = json.Marshal(t.EndAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'endAt': %w", err)
		}
	}

	object["requestId"], err = json.Marshal(t.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'requestId': %w", err)
	}

	object["scaledObject"], err = json.Marshal(t.ScaledObject)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'scaledObject': %w", err)
	}

	if t.StartAt != nil {
		object["startAt"], err = json.Marshal(t.StartAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'startAt': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *LaunchRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["duration"]; found {
		err = json.Unmarshal(raw, &t.Duration)
		if err != nil {
			return fmt.Errorf("error reading 'duration': %w", err)
		}
	}

	if raw, found := object["endAt"]; found {
		err = json.Unmarshal(raw, &t.EndAt)
		if err != nil {
			return fmt.Errorf("error reading 'endAt': %w", err)
		}
	}

	if raw, found := object["requestId"]; found {
		err = json.Unmarshal(raw, &t.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'requestId': %w", err)
		}
	}

	if raw, found := object["scaledObject"]; found {
		err = json.Unmarshal(raw, &t.ScaledObject)
		if err != nil {
			return fmt.Errorf("error reading 'scaledObject': %w", err)
		}
	}

	if raw, found := object["startAt"]; found {
		err = json.Unmarshal(raw, &t.StartAt)
		if err != nil {
			return fmt.Errorf("error reading 'startAt': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Accept a time-bounded launch request.
	// (POST /requests)
	PostRequests(ctx echo.Context) error
	// List ScaledObjects known to this receiver.
	// (GET /scaledobjects)
	ListScaledObjects(ctx echo.Context) error
	// Delete a request window for a known ScaledObject.
	// (DELETE /scaledobjects/{namespace}/{name}/requests/{requestId})
	DeleteScaledObjectRequest(ctx echo.Context, namespace string, name string, requestId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostRequests converts echo context to params.
func (w *ServerInterfaceWrapper) PostRequests(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostRequests(ctx)
	return err
}

// ListScaledObjects converts echo context to params.
func (w *ServerInterfaceWrapper) ListScaledObjects(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListScaledObjects(ctx)
	return err
}

// DeleteScaledObjectRequest converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteScaledObjectRequest(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "namespace" -------------
	var namespace string

	err = runtime.BindStyledParameterWithOptions("simple", "namespace", ctx.Param("namespace"), &namespace, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter namespace: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// ------------- Path parameter "requestId" -------------
	var requestId string

	err = runtime.BindStyledParameterWithOptions("simple", "requestId", ctx.Param("requestId"), &requestId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter requestId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteScaledObjectRequest(ctx, namespace, name, requestId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/requests", wrapper.PostRequests)
	router.GET(baseURL+"/scaledobjects", wrapper.ListScaledObjects)
	router.DELETE(baseURL+"/scaledobjects/:namespace/:name/requests/:requestId", wrapper.DeleteScaledObjectRequest)

}

type PostRequestsRequestObject struct {
	Body *PostRequestsJSONRequestBody
}

type PostRequestsResponseObject interface {
	VisitPostRequestsResponse(w http.ResponseWriter) error
}

type PostRequests202JSONResponse AcceptedRequest

func (response PostRequests202JSONResponse) VisitPostRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type PostRequests400JSONResponse ErrorResponse

func (response PostRequests400JSONResponse) VisitPostRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostRequests404JSONResponse ErrorResponse

func (response PostRequests404JSONResponse) VisitPostRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PostRequests408JSONResponse ErrorResponse

func (response PostRequests408JSONResponse) VisitPostRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(408)

	return json.NewEncoder(w).Encode(response)
}

type ListScaledObjectsRequestObject struct {
}

type ListScaledObjectsResponseObject interface {
	VisitListScaledObjectsResponse(w http.ResponseWriter) error
}

type ListScaledObjects200JSONResponse ScaledObjectList

func (response ListScaledObjects200JSONResponse) VisitListScaledObjectsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteScaledObjectRequestRequestObject struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
	RequestId string `json:"requestId"`
}

type DeleteScaledObjectRequestResponseObject interface {
	VisitDeleteScaledObjectRequestResponse(w http.ResponseWriter) error
}

type DeleteScaledObjectRequest200JSONResponse DeletedRequest

func (response DeleteScaledObjectRequest200JSONResponse) VisitDeleteScaledObjectRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteScaledObjectRequest404JSONResponse ErrorResponse

func (response DeleteScaledObjectRequest404JSONResponse) VisitDeleteScaledObjectRequestResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Accept a time-bounded launch request.
	// (POST /requests)
	PostRequests(ctx context.Context, request PostRequestsRequestObject) (PostRequestsResponseObject, error)
	// List ScaledObjects known to this receiver.
	// (GET /scaledobjects)
	ListScaledObjects(ctx context.Context, request ListScaledObjectsRequestObject) (ListScaledObjectsResponseObject, error)
	// Delete a request window for a known ScaledObject.
	// (DELETE /scaledobjects/{namespace}/{name}/requests/{requestId})
	DeleteScaledObjectRequest(ctx context.Context, request DeleteScaledObjectRequestRequestObject) (DeleteScaledObjectRequestResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostRequests operation middleware
func (sh *strictHandler) PostRequests(ctx echo.Context) error {
	var request PostRequestsRequestObject

	var body PostRequestsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostRequests(ctx.Request().Context(), request.(PostRequestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRequests")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostRequestsResponseObject); ok {
		return validResponse.VisitPostRequestsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListScaledObjects operation middleware
func (sh *strictHandler) ListScaledObjects(ctx echo.Context) error {
	var request ListScaledObjectsRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListScaledObjects(ctx.Request().Context(), request.(ListScaledObjectsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListScaledObjects")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListScaledObjectsResponseObject); ok {
		return validResponse.VisitListScaledObjectsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteScaledObjectRequest operation middleware
func (sh *strictHandler) DeleteScaledObjectRequest(ctx echo.Context, namespace string, name string, requestId string) error {
	var request DeleteScaledObjectRequestRequestObject

	request.Namespace = namespace
	request.Name = name
	request.RequestId = requestId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteScaledObjectRequest(ctx.Request().Context(), request.(DeleteScaledObjectRequestRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteScaledObjectRequest")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteScaledObjectRequestResponseObject); ok {
		return validResponse.VisitDeleteScaledObjectRequestResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXTW/bOBD9K8TsHhXL/TgsdMuiBTZAgBpJboUPY3JksZVILUklMAz99wVJWdGHAzuB",
	"G+yhN4vkDN88vnmk98B1VWtFylnI9mB5QRWGn9ecU+1I3NG/DVnnh1AI6aRWWK6Mrsk4SRayHEtLCdSD",
	"oT1QnhN38pG+KuG/c20qdJCBQEdXTlYECbhdTZCBdUaqLbTJc9S9Q+POjzMR403YajZrOZYkvm1+EA85",
	"/zSUQwZ/pM+1p13h6f1wbdulloYEZN8H20ySzpAnYwLWPWbdZU7gC5X0m95fRu9XY7S5I1trZemV7FZk",
	"LW7pSLUTxIeFxwDcYqN4ce7xakXfcsi+70f5RWPQh8C6TcYzpMS1g3W7nmLvQ3wdUt2S2roCsg/H5BBy",
	"vE0FJ1K/XRMJWH/E5wM7V0THzuh+AvMVGlFY0RlE+GW2Rn567aSO58CY5CT+W/lqFxnyEwako8q+9rw6",
	"VGgM7mZljLeY1+DXS5Xr0GvSlX7uJwm8KkP7kLkKGQz75+FhxQxxko9k2PXqBhJ4JGOD1GG5+LBYejC6",
	"JoW1hAw+LZaLT5BAja4INaWdNMJHrSNbno7QL17WsNLW3R1W9Yr/W4udX8u1cqQiyXVdSh4C0x82dlvk",
	"5xR7Y1tox3w501AYiLYVkH5cfrzY5tM7PWwvyHIj62ga8FAQi9yzrnz2hJZhF7nwJH9eLi8GaezTLwA6",
	"INlosWNCk2VKO1ah4wVzBUVxXK9uWMzKtGFCVygVM01JtgP9+X1BOzRbcmzYLkxG5D+VflLMaeYKaXtV",
	"dzD/el+YvJSk3OiwOSpOJQm2oVwbChQf5rluSj8xVIQ37aaq0Owg696NDJm366uNbpQgMZFUjEmjOehn",
	"/9nSkab0xnY/spFZh1xOjjNHPcLaCAzjjTGkXLlj+IiyxE1JLNemJ6wvxk6Z8vnZONmLwpjRle77G6KN",
	"v9ve4NJ9fwu24U0QnppzZuMTdIjgYAzeNg1W5MjY8CqRvnBvpYfrKBvdUGMLSwZkn7jzXsx88aTDh8Fb",
	"M69/ofIm/wdOOOGTVEI/hW6Npyv+PyY3EP/Nl5OWN2qJSALDaZ2+obDLMdzLx7ftfwEAAP//r9dp8MYO",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
