// Package httpreceiver provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpreceiver

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

// AcceptedRequest defines model for AcceptedRequest.
type AcceptedRequest struct {
	EffectiveEnd   time.Time    `json:"effectiveEnd"`
	EffectiveStart time.Time    `json:"effectiveStart"`
	RequestId      string       `json:"requestId"`
	ScaledObject   ScaledObject `json:"scaledObject"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// LaunchRequest defines model for LaunchRequest.
type LaunchRequest struct {
	Duration     *string      `json:"duration,omitempty"`
	EndAt        *time.Time   `json:"endAt,omitempty"`
	RequestId    string       `json:"requestId"`
	ScaledObject ScaledObject `json:"scaledObject"`
	StartAt      *time.Time   `json:"startAt,omitempty"`
	union        json.RawMessage
}

// LaunchRequest0 defines model for .
type LaunchRequest0 = interface{}

// LaunchRequest1 defines model for .
type LaunchRequest1 = interface{}

// ScaledObject defines model for ScaledObject.
type ScaledObject struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

// PostRequestsJSONRequestBody defines body for PostRequests for application/json ContentType.
type PostRequestsJSONRequestBody = LaunchRequest

// AsLaunchRequest0 returns the union data inside the LaunchRequest as a LaunchRequest0
func (t LaunchRequest) AsLaunchRequest0() (LaunchRequest0, error) {
	var body LaunchRequest0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLaunchRequest0 overwrites any union data inside the LaunchRequest as the provided LaunchRequest0
func (t *LaunchRequest) FromLaunchRequest0(v LaunchRequest0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLaunchRequest0 performs a merge with any union data inside the LaunchRequest, using the provided LaunchRequest0
func (t *LaunchRequest) MergeLaunchRequest0(v LaunchRequest0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLaunchRequest1 returns the union data inside the LaunchRequest as a LaunchRequest1
func (t LaunchRequest) AsLaunchRequest1() (LaunchRequest1, error) {
	var body LaunchRequest1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLaunchRequest1 overwrites any union data inside the LaunchRequest as the provided LaunchRequest1
func (t *LaunchRequest) FromLaunchRequest1(v LaunchRequest1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLaunchRequest1 performs a merge with any union data inside the LaunchRequest, using the provided LaunchRequest1
func (t *LaunchRequest) MergeLaunchRequest1(v LaunchRequest1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LaunchRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Duration != nil {
		object["duration"], err = json.Marshal(t.Duration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'duration': %w", err)
		}
	}

	if t.EndAt != nil {
		object["endAt"], err = json.Marshal(t.EndAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'endAt': %w", err)
		}
	}

	object["requestId"], err = json.Marshal(t.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'requestId': %w", err)
	}

	object["scaledObject"], err = json.Marshal(t.ScaledObject)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'scaledObject': %w", err)
	}

	if t.StartAt != nil {
		object["startAt"], err = json.Marshal(t.StartAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'startAt': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *LaunchRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["duration"]; found {
		err = json.Unmarshal(raw, &t.Duration)
		if err != nil {
			return fmt.Errorf("error reading 'duration': %w", err)
		}
	}

	if raw, found := object["endAt"]; found {
		err = json.Unmarshal(raw, &t.EndAt)
		if err != nil {
			return fmt.Errorf("error reading 'endAt': %w", err)
		}
	}

	if raw, found := object["requestId"]; found {
		err = json.Unmarshal(raw, &t.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'requestId': %w", err)
		}
	}

	if raw, found := object["scaledObject"]; found {
		err = json.Unmarshal(raw, &t.ScaledObject)
		if err != nil {
			return fmt.Errorf("error reading 'scaledObject': %w", err)
		}
	}

	if raw, found := object["startAt"]; found {
		err = json.Unmarshal(raw, &t.StartAt)
		if err != nil {
			return fmt.Errorf("error reading 'startAt': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Accept a time-bounded launch request.
	// (POST /requests)
	PostRequests(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostRequests converts echo context to params.
func (w *ServerInterfaceWrapper) PostRequests(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostRequests(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/requests", wrapper.PostRequests)

}

type PostRequestsRequestObject struct {
	Body *PostRequestsJSONRequestBody
}

type PostRequestsResponseObject interface {
	VisitPostRequestsResponse(w http.ResponseWriter) error
}

type PostRequests202JSONResponse AcceptedRequest

func (response PostRequests202JSONResponse) VisitPostRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type PostRequests400JSONResponse ErrorResponse

func (response PostRequests400JSONResponse) VisitPostRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostRequests408JSONResponse ErrorResponse

func (response PostRequests408JSONResponse) VisitPostRequestsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(408)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Accept a time-bounded launch request.
	// (POST /requests)
	PostRequests(ctx context.Context, request PostRequestsRequestObject) (PostRequestsResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PostRequests operation middleware
func (sh *strictHandler) PostRequests(ctx echo.Context) error {
	var request PostRequestsRequestObject

	var body PostRequestsJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostRequests(ctx.Request().Context(), request.(PostRequestsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRequests")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PostRequestsResponseObject); ok {
		return validResponse.VisitPostRequestsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xVy27bMBD8FWLbo2wrSQ+Fbi4QoAECxIh9C3ygyZXFVCJZcuXCMPTvBSn5IcWFnSDo",
	"zeLuDGeHQ3oHwlTWaNTkIduBFwVWPP6cCoGWUD7j7xo9hSUupSJlNC9nzlh0pNBDlvPSYwL2ZGkHmOco",
	"SG3wXsvwnRtXcYIMJCcckaoQEqCtRcjAk1N6DU1yRM2JO7oe51qND3GrN1UveInyafWKInJ+dZhDBl8m",
	"x9kn3eCT+Wlv01ErhxKyl5NtBqRvlCd9A5YHzaZjTuDeOeOe0VujPb7T3Qq952s8M+1A8b7xnIBHXmtR",
	"XHu8RuNTDtnLrscva8cDBJZN0q+gllOCZbMcaj9AwhxKP6JeUwHZzbk4RI6PpeAC9cczkYAPR3y9sGtD",
	"dO6M5gOZ78iI5hVeYURo85aLy72DOY7AluSM/gBROjcxp4rKUPuFko/KGD10o2iAYz8XixlzKFBt0LHp",
	"7AES2KDzMSaQjm/GadBqLGpuFWRwN07Hd5CA5VTEaSedrfHDmjbQwY6YtRAJmBlPz/uuQ1p+GLkNvcJo",
	"Qt2abG2pRAROXn2b1DYLl5LSv1JN3zJyNcaF9spHpbfp7adtPnyw4/YSvXDKthcOFgWy1nvWjc/+cM94",
	"hxwHk7+l6adJ6r9x/xC0V7IycsukQc+0IVZxEgWjAttwTGcPrGVlxjFpKq40c3WJvhP9/f+KFqVCTT0X",
	"BdcCS5RshblxGLXv68LUZSicWh1ekrqquNtC1v3bMs7CGzJamVpLlIOzCpim+RsAAP//MO57MbMHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
