// Package httpclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package httpclient

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// AcceptedRequest defines model for AcceptedRequest.
type AcceptedRequest struct {
	EffectiveEnd   time.Time    `json:"effectiveEnd"`
	EffectiveStart time.Time    `json:"effectiveStart"`
	RequestId      string       `json:"requestId"`
	ScaledObject   ScaledObject `json:"scaledObject"`
}

// DeletedRequest defines model for DeletedRequest.
type DeletedRequest struct {
	EffectiveEnd   time.Time    `json:"effectiveEnd"`
	EffectiveStart time.Time    `json:"effectiveStart"`
	RequestId      string       `json:"requestId"`
	ScaledObject   ScaledObject `json:"scaledObject"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// LaunchRequest defines model for LaunchRequest.
type LaunchRequest struct {
	Duration     *string      `json:"duration,omitempty"`
	EndAt        *time.Time   `json:"endAt,omitempty"`
	RequestId    string       `json:"requestId"`
	ScaledObject ScaledObject `json:"scaledObject"`
	StartAt      *time.Time   `json:"startAt,omitempty"`
	union        json.RawMessage
}

// LaunchRequest0 defines model for .
type LaunchRequest0 = interface{}

// LaunchRequest1 defines model for .
type LaunchRequest1 = interface{}

// ScaledObject defines model for ScaledObject.
type ScaledObject struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
}

// ScaledObjectList defines model for ScaledObjectList.
type ScaledObjectList struct {
	ScaledObjects []ScaledObject `json:"scaledObjects"`
}

// PostRequestsJSONRequestBody defines body for PostRequests for application/json ContentType.
type PostRequestsJSONRequestBody = LaunchRequest

// AsLaunchRequest0 returns the union data inside the LaunchRequest as a LaunchRequest0
func (t LaunchRequest) AsLaunchRequest0() (LaunchRequest0, error) {
	var body LaunchRequest0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLaunchRequest0 overwrites any union data inside the LaunchRequest as the provided LaunchRequest0
func (t *LaunchRequest) FromLaunchRequest0(v LaunchRequest0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLaunchRequest0 performs a merge with any union data inside the LaunchRequest, using the provided LaunchRequest0
func (t *LaunchRequest) MergeLaunchRequest0(v LaunchRequest0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLaunchRequest1 returns the union data inside the LaunchRequest as a LaunchRequest1
func (t LaunchRequest) AsLaunchRequest1() (LaunchRequest1, error) {
	var body LaunchRequest1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLaunchRequest1 overwrites any union data inside the LaunchRequest as the provided LaunchRequest1
func (t *LaunchRequest) FromLaunchRequest1(v LaunchRequest1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLaunchRequest1 performs a merge with any union data inside the LaunchRequest, using the provided LaunchRequest1
func (t *LaunchRequest) MergeLaunchRequest1(v LaunchRequest1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LaunchRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Duration != nil {
		object["duration"], err = json.Marshal(t.Duration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'duration': %w", err)
		}
	}

	if t.EndAt != nil {
		object["endAt"], err = json.Marshal(t.EndAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'endAt': %w", err)
		}
	}

	object["requestId"], err = json.Marshal(t.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'requestId': %w", err)
	}

	object["scaledObject"], err = json.Marshal(t.ScaledObject)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'scaledObject': %w", err)
	}

	if t.StartAt != nil {
		object["startAt"], err = json.Marshal(t.StartAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'startAt': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *LaunchRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["duration"]; found {
		err = json.Unmarshal(raw, &t.Duration)
		if err != nil {
			return fmt.Errorf("error reading 'duration': %w", err)
		}
	}

	if raw, found := object["endAt"]; found {
		err = json.Unmarshal(raw, &t.EndAt)
		if err != nil {
			return fmt.Errorf("error reading 'endAt': %w", err)
		}
	}

	if raw, found := object["requestId"]; found {
		err = json.Unmarshal(raw, &t.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'requestId': %w", err)
		}
	}

	if raw, found := object["scaledObject"]; found {
		err = json.Unmarshal(raw, &t.ScaledObject)
		if err != nil {
			return fmt.Errorf("error reading 'scaledObject': %w", err)
		}
	}

	if raw, found := object["startAt"]; found {
		err = json.Unmarshal(raw, &t.StartAt)
		if err != nil {
			return fmt.Errorf("error reading 'startAt': %w", err)
		}
	}

	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostRequestsWithBody request with any body
	PostRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostRequests(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListScaledObjects request
	ListScaledObjects(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteScaledObjectRequest request
	DeleteScaledObjectRequest(ctx context.Context, namespace string, name string, requestId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostRequestsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostRequests(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostRequestsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListScaledObjects(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListScaledObjectsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteScaledObjectRequest(ctx context.Context, namespace string, name string, requestId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteScaledObjectRequestRequest(c.Server, namespace, name, requestId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostRequestsRequest calls the generic PostRequests builder with application/json body
func NewPostRequestsRequest(server string, body PostRequestsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostRequestsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostRequestsRequestWithBody generates requests for PostRequests with any type of body
func NewPostRequestsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/requests")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListScaledObjectsRequest generates requests for ListScaledObjects
func NewListScaledObjectsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/scaledobjects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteScaledObjectRequestRequest generates requests for DeleteScaledObjectRequest
func NewDeleteScaledObjectRequestRequest(server string, namespace string, name string, requestId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "namespace", namespace, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "name", name, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "requestId", requestId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/scaledobjects/%s/%s/requests/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostRequestsWithBodyWithResponse request with any body
	PostRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error)

	PostRequestsWithResponse(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error)

	// ListScaledObjectsWithResponse request
	ListScaledObjectsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListScaledObjectsResponse, error)

	// DeleteScaledObjectRequestWithResponse request
	DeleteScaledObjectRequestWithResponse(ctx context.Context, namespace string, name string, requestId string, reqEditors ...RequestEditorFn) (*DeleteScaledObjectRequestResponse, error)
}

type PostRequestsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *AcceptedRequest
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
	JSON408      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostRequestsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostRequestsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListScaledObjectsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ScaledObjectList
}

// Status returns HTTPResponse.Status
func (r ListScaledObjectsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListScaledObjectsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteScaledObjectRequestResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeletedRequest
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteScaledObjectRequestResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteScaledObjectRequestResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostRequestsWithBodyWithResponse request with arbitrary body returning *PostRequestsResponse
func (c *ClientWithResponses) PostRequestsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error) {
	rsp, err := c.PostRequestsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestsResponse(rsp)
}

func (c *ClientWithResponses) PostRequestsWithResponse(ctx context.Context, body PostRequestsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostRequestsResponse, error) {
	rsp, err := c.PostRequests(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostRequestsResponse(rsp)
}

// ListScaledObjectsWithResponse request returning *ListScaledObjectsResponse
func (c *ClientWithResponses) ListScaledObjectsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListScaledObjectsResponse, error) {
	rsp, err := c.ListScaledObjects(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListScaledObjectsResponse(rsp)
}

// DeleteScaledObjectRequestWithResponse request returning *DeleteScaledObjectRequestResponse
func (c *ClientWithResponses) DeleteScaledObjectRequestWithResponse(ctx context.Context, namespace string, name string, requestId string, reqEditors ...RequestEditorFn) (*DeleteScaledObjectRequestResponse, error) {
	rsp, err := c.DeleteScaledObjectRequest(ctx, namespace, name, requestId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteScaledObjectRequestResponse(rsp)
}

// ParsePostRequestsResponse parses an HTTP response from a PostRequestsWithResponse call
func ParsePostRequestsResponse(rsp *http.Response) (*PostRequestsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostRequestsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest AcceptedRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	}

	return response, nil
}

// ParseListScaledObjectsResponse parses an HTTP response from a ListScaledObjectsWithResponse call
func ParseListScaledObjectsResponse(rsp *http.Response) (*ListScaledObjectsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListScaledObjectsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ScaledObjectList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteScaledObjectRequestResponse parses an HTTP response from a DeleteScaledObjectRequestWithResponse call
func ParseDeleteScaledObjectRequestResponse(rsp *http.Response) (*DeleteScaledObjectRequestResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteScaledObjectRequestResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeletedRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xXTW/bOBD9K8TsHhXL/TgsdMuiBTZAgBpJboUPY3JksZVILUklMAz99wVJWdGHAzuB",
	"G+yhN4vkDN88vnmk98B1VWtFylnI9mB5QRWGn9ecU+1I3NG/DVnnh1AI6aRWWK6Mrsk4SRayHEtLCdSD",
	"oT1QnhN38pG+KuG/c20qdJCBQEdXTlYECbhdTZCBdUaqLbTJc9S9Q+POjzMR403YajZrOZYkvm1+EA85",
	"/zSUQwZ/pM+1p13h6f1wbdulloYEZN8H20ySzpAnYwLWPWbdZU7gC5X0m95fRu9XY7S5I1trZemV7FZk",
	"LW7pSLUTxIeFxwDcYqN4ce7xakXfcsi+70f5RWPQh8C6TcYzpMS1g3W7nmLvQ3wdUt2S2roCsg/H5BBy",
	"vE0FJ1K/XRMJWH/E5wM7V0THzuh+AvMVGlFY0RlE+GW2Rn567aSO58CY5CT+W/lqFxnyEwako8q+9rw6",
	"VGgM7mZljLeY1+DXS5Xr0GvSlX7uJwm8KkP7kLkKGQz75+FhxQxxko9k2PXqBhJ4JGOD1GG5+LBYejC6",
	"JoW1hAw+LZaLT5BAja4INaWdNMJHrSNbno7QL17WsNLW3R1W9Yr/W4udX8u1cqQiyXVdSh4C0x82dlvk",
	"5xR7Y1tox3w501AYiLYVkH5cfrzY5tM7PWwvyHIj62ga8FAQi9yzrnz2hJZhF7nwJH9eLi8GaezTLwA6",
	"INlosWNCk2VKO1ah4wVzBUVxXK9uWMzKtGFCVygVM01JtgP9+X1BOzRbcmzYLkxG5D+VflLMaeYKaXtV",
	"dzD/el+YvJSk3OiwOSpOJQm2oVwbChQf5rluSj8xVIQ37aaq0Owg696NDJm366uNbpQgMZFUjEmjOehn",
	"/9nSkab0xnY/spFZh1xOjjNHPcLaCAzjjTGkXLlj+IiyxE1JLNemJ6wvxk6Z8vnZONmLwpjRle77G6KN",
	"v9ve4NJ9fwu24U0QnppzZuMTdIjgYAzeNg1W5MjY8CqRvnBvpYfrKBvdUGMLSwZkn7jzXsx88aTDh8Fb",
	"M69/ofIm/wdOOOGTVEI/hW6Npyv+PyY3EP/Nl5OWN2qJSALDaZ2+obDLMdzLx7ftfwEAAP//r9dp8MYO",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
